Fix pdf links
scipy/docs.scipy.org pull request #56
Opened 2021-09-14 21:45 UTC by ivanistheone

currently:

numpy/numpy-ref-1.17.0.pdf  
is  
https://docs.scipy.org/doc/numpy/numpy-ref-1.17.0.pdf  
-->  
https://numpy.org/doc/stable/numpy-ref-1.17.0.pdf  
which 404s

this is an attempt to fix this by removing version number, but still using the /doc/numpy/ -->   https://numpy.org/doc/stable/  redirect

2021-09-15 07:24 UTC, tupui requested changes
Thanks @ivanistheone. NumPy links resolve correctly, but the SciPy one does not.

2021-09-15 07:24 UTC, tupui commented on index.rst
> +          <a href="scipy/scipy-ref.pdf">[PDF]</a></span>
This does not look correct. `https://docs.scipy.org/doc/scipy/scipy-ref.pdf` returns 404

2021-09-15 11:48 UTC, tupuinui approved these changes
LGTM, thanks.

2021-09-15 11:49 UTC, merged

2021-09-15 11:52 UTC, tupuinui commented
@rgommers is the deployment only manual here?

2021-09-15 12:21 UTC, rgommers commented
Yes indeed. Our docs deploys for anything that lives on https://docs.scipy.org/doc/ are manual. I'll have a look at deploying this change later.

2021-09-17 16:26 UTC, rgommers commented
deployed now